# Default values for desafio16-17.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates
# Default values for desafio16-17.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#inicio de values personalizados
metadata:
  name: docker-no-plex
# labels:
#   app: docker-on-plex
#spec:
# replicas: 1
# selector:
#  matchLabels:
#     app: docker-on-plex
# template:
#   metadata:
#     labels:
#       app: docker-on-plex
#   spec:
#     containers:
# - name: docker-on-plex
#   image: florpezz/plex_on_docker:2
#   ports:
#   - containerPort: 32400
